environment: stage

deployment:
  image:
    tag: 0
  replicas: 1
  env:
    redis_host: master.autom8-hard-stage-elascache-rep-group.p7r3l6.use1.cache.amazonaws.com

secret:
  redis_pass: automate-all-the-things-stage
